### PR TITLE
CSS Update

### PR DESCRIPTION
**Pull request by mooreaa13**
Update CSS styles and main page.

### CODE REVIEW

**Comment by mkstoyanov** [comment]
OK to test!

**Comment by mkstoyanov** [comment]
OK to test.

**Comment by mkstoyanov** [comment]
@dalg24 Did they change the "OK to test" command for Jenkins?

**Comment by mkstoyanov** [comment]
@dalg24 No, I have no messed with jenkins.

**Comment by mkstoyanov** [comment]
test this please

**Comment by dalg24** [comment]
test this please

**Comment by dalg24** [comment]
ok to test

**Comment by mkstoyanov** [comment]
OK to test!

**Comment by dalg24** [comment]
ok to test

**Comment by mkstoyanov** [comment]
retest this please

**Pull request merged**
