### PR TITLE
Update random engine

### PR DESCRIPTION
**Pull request by mkstoyanov**
* switched sparse grid testing to implementation independent random number generator
* updated the dream random seed selection

### CODE REVIEW

**Comment by mkstoyanov** [comment]
@dalg24 I am getting this failed build, but only gibberish when I try to get to the ctest console output. All tests pass on my machine with and without docker.

**Comment by dalg24** [comment]
> @dalg24 I am getting this failed build, but only gibberish when I try to get to the ctest console output. All tests pass on my machine with and without docker.

Just saw what got printed on the [standard output](https://cloud.cees.ornl.gov/jenkins-ci/job/Tasmanian-GCC54-CUDA90/343/testReport/projectroot/SparseGrids/SparseGridsAcceleration/)  and yes that's not very helpful.  I am not sure what the issue is.  How urgent is this?  Do you have access to a machine that has nvidia-docker?

**Comment by mkstoyanov** [comment]
It is not too urgent.

I have nvidia-docker installed on my workstation, but the problem doesn't appear here. In fact, the PR passes all nightly tests. 

Could this be the case of someone else using the GPUs and running out of RAM? The test that is failing is the C++/CUDA test with larger problems, the Python/CUDA test passed and those run smaller problems.

**Comment by mkstoyanov** [comment]
I'll merge the PR, it will go through the nightly tests, I can revert it tomorrow if I get a report for an error.

`ERROR: cuda failed at CudaVector::resize(), call to cudaMalloc() with error: out of memory`

**Pull request merged**
